name: Deployment

on:
  workflow_dispatch:

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel deployment
        env:
          DEPLOY_HOOK: ${{ secrets.VERCEL_PATH }}
        run: curl -X POST "$DEPLOY_HOOK"
